services:
  minecraft:
    image: itzg/minecraft-server:java21-graalvm
    restart: always
    tty: true
    stdin_open: true
    container_name: fpc-minecraft
    labels:
      - docker-volume-backup.stop-during-backup=true
      - docker-volume-backup.archive-pre=sh /pre-backup.sh
    environment:
      EULA: true
      TYPE: FABRIC
      MEMORY: 14G
      VERSION: "1.21.8"
      USE_MEOWICE_GRAALVM_FLAGS: true
      GUI: false
      MOTD: \u00A7l\u00A75~\u00A7d🌸 Petals' Craft 🌸\u00A75~
      SERVER_NAME: Petals' Craft
      ICON: /icon.png
      OVERRIDE_ICON: true
      MAX_PLAYERS: 128
      SPAWN_PROTECTION: 0
      ENFORCE_SECURE_PROFILE: false
      BROADCAST_CONSOLE_TO_OPS: true
      BROADCAST_RCON_TO_OPS: true
      SIMULATION_DISTANCE: 10
      VIEW_DISTANCE: 10
      DIFFICULTY: normal
      ENABLE_WHITELIST: true
      WHITELIST: ${MC_WHITELIST}
      OPS: |-
        iBiixie
      ENABLE_RCON: true
      MODS: |-
        https://ci.lucko.me/job/LuckPermsPlaceholders/12/artifact/fabric-placeholderapi/build/libs/LuckPerms-Fabric-PlaceholderAPI-Hook.jar
      MODRINTH_PROJECTS: |-
        fabric-api:jjBL6OsN
        fabric-language-kotlin:mccDBWqV
        lithium:pDfTqezk
        yacl:WxYlHLu6
        debugify:WLSwJeXa
        ferrite-core:CtMpt7Jr
        luckperms:uStOaYyZ
        placeholder-api:wg33PHxj
        styled-chat:4iEiOcnO
        polymer:6cqgmDx1
        universal-graves:gdZmLCZD
        collective:mld0ZPD9
        tree-harvester:LG3WQ1fx
        chunky:inWDi2cf
        teleport-commands:P4t70i1a
        ledger:f3h7no4G
        spark:3KCl7Vx0
        bluemap:plVwynim
        bluemap-offline-player-markers-(fabric):w8iZe7gX
        c2me-fabric:tlZRTK1v
        scalablelux:Bi5i8Ema
        inventory-totem:EKYaWQlO
        recast:DRurPuCn
        double-doors:Kaxph4k0
      RCON_CMDS_STARTUP: |-
        gamerule doFireTick false
        gamerule mobGriefing false
        gamerule playersSleepingPercentage 25
      RCON_CMDS_FIRST_CONNECT: |-
        chunky pause
      RCON_CMDS_LAST_DISCONNECT: |-
        chunky continue
    ports:
      - 44730:25565
    expose:
      - 8100
    networks:
      - public
      - proxied
    volumes:
      - /mnt/block-callisto/fpc-minecraft/minecraft:/data
      - /mnt/block-callisto/fpc-minecraft/icon.png:/icon.png
      - /mnt/block-callisto/fpc-minecraft/pre-backup.sh:/pre-backup.sh

  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.{{ .Extension }}
      BACKUP_CRON_EXPRESSION: "0 45 8 * * *"
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: '90'
      AWS_ENDPOINT: ${S3_ENDPOINT}:${S3_PORT}
      AWS_ENDPOINT_PROTO: https
      AWS_S3_BUCKET_NAME: ${S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${S3_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET}
      BACKUP_COMPRESSION: zst
      GIZ_PARELLELISM: 0
      env_file: .env
    volumes:
      - /mnt/block-callisto/fpc-minecraft/minecraft/world:/backup/minecraft/world:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/logs:/backup/minecraft/logs:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/config:/backup/minecraft/config:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/mods:/backup/minecraft/mods:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/banned-ips.json:/backup/minecraft/banned-ips.json:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/banned-players.json:/backup/minecraft/banned-players.json:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/ops.json:/backup/minecraft/ops.json:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/whitelist.json:/backup/minecraft/whitelist.json:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/server-icon.png:/backup/minecraft/server-icon.png:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/eula.txt:/backup/minecraft/eula.txt:ro
      - /mnt/block-callisto/fpc-minecraft/minecraft/fstats.log:/backup/minecraft/fstats.log:ro
      - /mnt/block-callisto/fpc-minecraft/icon.png:/backup/icon.png:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  public:
    name: public
    external: true
  proxied:
    name: proxied
    external: true

