name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v5
        
    - name: 'Compose Deploy'
      uses: cssnr/stack-deploy-action@v1
      with:
        name: 'fpc-minecraft'
        file: 'compose.yaml'
        host: ${{ secrets.DOCKER_HOST }}
        port: ${{ vars.DOCKER_PORT }}
        user: ${{ secrets.DOCKER_USER }}
        ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
        mode: compose
        args: --remove-orphans --force-recreate
      env:
        S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
        S3_PORT: ${{ vars.S3_PORT }}
        S3_BUCKET: ${{ vars.S3_BUCKET }}
        S3_KEY: ${{ secrets.S3_KEY }}
        S3_SECRET: ${{ secrets.S3_SECRET }}
